paginate: 10 # pagination based on number of posts
paginate_path: "page:num"
exclude: ["README.md"] # files to exclude
title: iToast Toastmasters Club

defaults:
  -
    scope:
      path: ""
    values:
      title: iToast Toastmasters Club

author:
  name: iToast
  email: amesitoast@gmail.com
  facebook: 309775882396264
  github: itoastames
  bio: Where Leaders Are Made


rss_path: feed.xml


BASE_PATH:

gems:
  - jekyll-paginate
  - jekyll-seo-tag

